### ISSUE TITLE
Setup failed! -1

### ISSUE THREAD

**Issue by skrixx** [aws/aws-iot-device-sdk-arduino-yun#50]
Hello, I want to use Amazon AWS IoT with my Arduino Yun, but it failed still after 4 Days working. I got some fails and follows instruktions from #28 and #25 but no success. fresh openWRT is installed.

First I got this: 
> root@ichair:~/AWS-IoT-Python-Runtime/runtime# 
/bin/ash: 1: not found
/bin/ash: /root: Permission denied
/bin/ash: 1: not found
/bin/ash: /root: Permission denied
/bin/ash: 1: not found
/bin/ash: /root: Permission denied
/bin/ash: 1: not found
/bin/ash: /root: Permission denied
Linux
/

>I T

>G T

>Connect failed!
-1

Then I installed the python SDK and let basicPubSub sample running and got this:

> root@Arduino:~/aws-iot-device-sdk-python-master/samples/basicPubSub# python basicPubSub.py -e <random>.iot.eu-central-1.amazonaws.com -r /root/AWS-IoT-
Python-Runtime/certs/rootCA.crt -c /root/AWS-IoT-Python-Runtime/certs/<random>-certificate.pem.crt -k /root/AWS-IoT-Python-Runtime/certs/<random>-private
.pem.key
2017-06-23 13:04:22,960 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Paho MQTT Client init.
2017-06-23 13:04:22,963 - AWSIoTPythonSDK.core.protocol.mqttCore - INFO - ClientID: basicPubSub
2017-06-23 13:04:22,967 - AWSIoTPythonSDK.core.protocol.mqttCore - INFO - Protocol: MQTTv3.1.1
2017-06-23 13:04:22,970 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Register Paho MQTT Client callbacks.
2017-06-23 13:04:22,974 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - mqttCore init.
2017-06-23 13:04:22,978 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Load CAFile from: /root/AWS-IoT-Python-Runtime/certs/rootCA.crt
2017-06-23 13:04:22,981 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Load Key from: /root/AWS-IoT-Python-Runtime/certs/454c742925-private.pem.key
2017-06-23 13:04:22,985 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Load Cert from: /root/AWS-IoT-Python-Runtime/certs/454c742925-certificate.pem.crt
2017-06-23 13:04:22,988 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Custom setting for backoff timing: baseReconnectTime = 1 sec
2017-06-23 13:04:22,992 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Custom setting for backoff timing: maximumReconnectTime = 32 sec
2017-06-23 13:04:22,996 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Custom setting for backoff timing: minimumConnectTime = 20 sec
2017-06-23 13:04:23,000 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Custom setting for publish queueing: queueSize = -1
2017-06-23 13:04:23,003 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Custom setting for publish queueing: dropBehavior = Drop Newest
2017-06-23 13:04:23,007 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Custom setting for draining interval: 0.5 sec
2017-06-23 13:04:23,011 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Set maximum connect/disconnect timeout to be 10 second.
2017-06-23 13:04:23,015 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Set maximum MQTT operation timeout to be 5 second
2017-06-23 13:04:23,019 - AWSIoTPythonSDK.core.protocol.mqttCore - INFO - Connection type: TLSv1.2 Mutual Authentication
Traceback (most recent call last):
  File "basicPubSub.py", line 87, in <module>
    myAWSIoTMQTTClient.connect()
  File "/usr/lib/python2.7/site-packages/AWSIoTPythonSDK/MQTTLib.py", line 405, in connect
    return self._mqttCore.connect(keepAliveIntervalSecond)
  File "/usr/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/mqttCore.py", line 290, in connect
    self._pahoClient.connect(self._host, self._port, keepAliveInterval)  # Throw exception...
  File "/usr/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 655, in connect
    return self.reconnect()
  File "/usr/lib/python2.7/site-packages/AWSIoTPythonSDK/core/protocol/paho/client.py", line 777, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
socket.error: [Errno 145] Connection timed out

What doese this meen? 
And if now the Arduino SDK is running I got a different failure:

>AWS IoT SDK Version(dev) 2.2.0-

>root@Arduino:~/AWS-IoT-Python-Runtime/runtime# 
/bin/ash: 1: not found
/bin/ash: /root: Permission denied
/bin/ash: 1: not found
/bin/ash: /root: Permission denied
/bin/ash: 1: not found
/bin/ash: /root: Permission denied
/bin/ash: 1: not found
/bin/ash: /root: Permission denied
Linux
/

>Traceback (most recent call last):
Setup failed!
-1

I really dont know what can I do more, can somebody help me?
Maybee @liuszeng ?

Thanks
Skrixx

**Comment by liuszeng** [comment]
Hi @skrixx ,

Thank you very much for using AWS IoT Arduino Yun SDK.

It seems that the Python runtime failed in connecting to AWS IoT at TCP connection level. You can try the following:
1. Double check your AWS IoT endpoint. It should have the following format:
```
<CUSTOMER_SPECIFIC_PREFIX>.iot.<REGION>.amazonaws.com
```
If you are using X.509 certificate auth., you should use port 8883. If you are using MQTT over WebSocket, you should use port 443.

2. On your AR9331 (where OpenWRT lives), try a simple telnet command to the service hostname and port:
```
host$> telnet <prefix>.iot.<region>.amazonaws.com 8883
Trying 54.236.141.103...
Connected to <endpoint>.
Escape character is '^]'.

Connection closed by foreign host.
host$>
```
The above shows a successful TCP connection, with the connection eventually being closed due to failed authentication. This would indicate connections on port 8883 are not being blocked. Below shows the same command when attempting on a blocked port:
```
host$> telnet <prefix>.iot.<region>.amazonaws.com 8883
Trying 54.236.141.103...
telnet: connect to address 54.236.141.103: Connection refused
```
Check your DNS configuration or try connecting from a different network.

Thanks,
Liusu

**Comment by skrixx** [comment]
Changing port between 443 and 8883 make no difference and the endpoint is correct.
Then I tryed a simple telnet command an got this:

>root@Arduino:~# telnet <prefix>.iot.eu-central-1.amazonaws.com 8883
telnet: can't connect to remote host (35.157.199.74): Connection timed out

Is this a network problem?

Kind regards

**Comment by liuszeng** [comment]
Hi @skrixx ,

Thanks for providing the information.

A failure in `telnet` command means that a TCP connection to your AWS IoT endpoint cannot be established from your board. To verify if it is a network specific issue, you can try the same command on another device/computer that is connected to the same network Yun is on. If you are still experiencing this issue, you may want to try again with a different network.

Thanks,
Liusu

**Comment by Shang3221** [comment]
Hi @ Liusu,

I am experiencing the same error setup fail! -1. But I have validated all my certificates using the python SDK program basicPubSub.py and gotten the results below. But with the same certificates and root directory, I am not able to get my Arduino Yun running. Please see below for the basicPubSub.py results, appreciate your help to advise as I have go thru all issues raised here regarding this but still couldn't resolve it. 

**Results from running basicPubSub.py**

root@Yunduino:~/aws-iot-device-sdk-python-latest/samples/basicPubSub# python basicPubSub.py -e a1qsl6fi3i7jvl.iot.ap-southeast-1.amazonaws.
com -r /root/AWS-IoT-Python-Runtime/certs/CAroot.pem -c /root/AWS-IoT-Python-Runtime/certs/FirstAWSIoTcertificate.pem.crt -k /root/AWS-IoT-Python-R
untime/certs/FirstAWSIoTprivate.pem.key
2017-07-02 09:43:16,373 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Paho MQTT Client init.
2017-07-02 09:43:16,376 - AWSIoTPythonSDK.core.protocol.mqttCore - INFO - ClientID: basicPubSub
2017-07-02 09:43:16,380 - AWSIoTPythonSDK.core.protocol.mqttCore - INFO - Protocol: MQTTv3.1.1
2017-07-02 09:43:16,383 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Register Paho MQTT Client callbacks.
2017-07-02 09:43:16,386 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - mqttCore init.
2017-07-02 09:43:16,389 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Load CAFile from: /root/AWS-IoT-Python-Runtime/certs/CAroot.pem
2017-07-02 09:43:16,391 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Load Key from: /root/AWS-IoT-Python-Runtime/certs/FirstAWSIoTprivate.pem          .key
2017-07-02 09:43:16,396 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Load Cert from: /root/AWS-IoT-Python-Runtime/certs/FirstAWSIoTcertificat          e.pem.crt
2017-07-02 09:43:16,400 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Custom setting for backoff timing: baseReconnectTime = 1 sec
2017-07-02 09:43:16,403 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Custom setting for backoff timing: maximumReconnectTime = 32 sec
2017-07-02 09:43:16,407 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Custom setting for backoff timing: minimumConnectTime = 20 sec
2017-07-02 09:43:16,411 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Custom setting for publish queueing: queueSize = -1
2017-07-02 09:43:16,414 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Custom setting for publish queueing: dropBehavior = Drop Newest
2017-07-02 09:43:16,417 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Custom setting for draining interval: 0.5 sec
2017-07-02 09:43:16,420 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Set maximum connect/disconnect timeout to be 10 second.
2017-07-02 09:43:16,422 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Set maximum MQTT operation timeout to be 5 second
2017-07-02 09:43:16,432 - AWSIoTPythonSDK.core.protocol.mqttCore - INFO - Connection type: TLSv1.2 Mutual Authentication
2017-07-02 09:43:18,758 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Connect result code 0
2017-07-02 09:43:18,762 - AWSIoTPythonSDK.core.protocol.mqttCore - INFO - Connected to AWS IoT.
2017-07-02 09:43:18,772 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Connect time consumption: 50.0ms.
2017-07-02 09:43:18,781 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Started a subscribe request 1
2017-07-02 09:43:18,806 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - _resubscribeCount: -1
2017-07-02 09:43:18,808 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Subscribe request 1 sent.
2017-07-02 09:43:18,813 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Subscribe request 1 succeeded. Time consumption: 20.0ms.
2017-07-02 09:43:18,816 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Recover subscribe context for the next request: subscribeSent: False
2017-07-02 09:43:20,827 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Try to put a publish request 2 in the TCP stack.
2017-07-02 09:43:20,830 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Publish request 2 succeeded.
Received a new message:
New Message 0
from topic:
sdk/test/Python
--------------


2017-07-02 09:43:21,838 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Try to put a publish request 3 in the TCP stack.
2017-07-02 09:43:21,840 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Publish request 3 succeeded.
Received a new message:
New Message 1
from topic:
sdk/test/Python
--------------


2017-07-02 09:43:22,849 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Try to put a publish request 4 in the TCP stack.
2017-07-02 09:43:22,852 - AWSIoTPythonSDK.core.protocol.mqttCore - DEBUG - Publish request 4 succeeded.
Received a new message:
New Message 2
from topic:
sdk/test/Python
--------------

**Comment by vareddy-zz** [comment]
Hi @skrixx,
We haven't heard from you in over two months and hence we are closing this issue. If you have any questions about the Arduino SDK, please feel free to open another issue. 
Thanks!
Varun
